library(robotstxt)
path<-paths_allowed("https://www.imdb.com/search/title/?groups=top_250&sort=user_rating")
library(rvest)
link<-"https://www.imdb.com/search/title/?groups=top_250&sort=user_rating"
web<-read_html(link)
library(dplyr)
movies<-web%>%html_nodes(".lister-item-header a")%>%html_text()
ratings<-web%>%html_nodes(".ratings-imdb-rating strong")%>%html_text()
year<-web%>%html_nodes(".text-muted.unbold")%>%html_text()
View(movies)
View(ratings)
View(year)
final<-data.frame(movies,ratings,year)
View(final)
write.csv(final,"Movies2.csv")